# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dBiCopMar_cpp <- function(xx, yy, cop_family, cop_param, marg_family, mar_param, ce = FALSE, logd = FALSE) {
    .Call(`_dnnmp_dBiCopMar_cpp`, xx, yy, cop_family, cop_param, marg_family, mar_param, ce, logd)
}

dBiCopMar_cpp2 <- function(xx, yy, cop_family, cop_param, marg_family, mar_param, ce = FALSE, logd = FALSE) {
    .Call(`_dnnmp_dBiCopMar_cpp2`, xx, yy, cop_family, cop_param, marg_family, mar_param, ce, logd)
}

updateFullCopLabel <- function(yy, yy_ne, nne, weight, rho, cop_family, marg_family, yy_param1, yy_param2, yy_ne_param1, yy_ne_param2, logit_mu, logit_ka, cutoff) {
    .Call(`_dnnmp_updateFullCopLabel`, yy, yy_ne, nne, weight, rho, cop_family, marg_family, yy_param1, yy_param2, yy_ne_param1, yy_ne_param2, logit_mu, logit_ka, cutoff)
}

updateCeCopAux <- function(yy, oo, rho, ne_label, cop_family, mar_family, yy_param1, yy_param2) {
    .Call(`_dnnmp_updateCeCopAux`, yy, oo, rho, ne_label, cop_family, mar_family, yy_param1, yy_param2)
}

pCopPoNNMP_ref_simple <- function(obs, cop_family, cop_param, ref_ne, ref_ne_idx, oo, th, weight) {
    .Call(`_dnnmp_pCopPoNNMP_ref_simple`, obs, cop_family, cop_param, ref_ne, ref_ne_idx, oo, th, weight)
}

pCopNbNNMP_ref_covar <- function(obs, cop_family, cop_param, ref_XX, ref_ne, ref_ne_idx, oo, bb, size, weight) {
    .Call(`_dnnmp_pCopNbNNMP_ref_covar`, obs, cop_family, cop_param, ref_XX, ref_ne, ref_ne_idx, oo, bb, size, weight)
}

refNe <- function(nne, coords, obs) {
    .Call(`_dnnmp_refNe`, nne, coords, obs)
}

gridNe <- function(nne, coords, grid, obs) {
    .Call(`_dnnmp_gridNe`, nne, coords, grid, obs)
}

predCeCopNNMP_simple <- function(obs, cop_family, cop_param, marg_family, marg_param, nne, DD, zeta, ga, kasq, oo, grid_ne_idx, grid_ne_dist, probs, lb, ub, tol, maxit, nreport, verbose = TRUE, sam = FALSE) {
    .Call(`_dnnmp_predCeCopNNMP_simple`, obs, cop_family, cop_param, marg_family, marg_param, nne, DD, zeta, ga, kasq, oo, grid_ne_idx, grid_ne_dist, probs, lb, ub, tol, maxit, nreport, verbose, sam)
}

predCeCopNNMP_covars <- function(obs, cop_family, cop_param, marg_family, ref_marg_param1, ref_marg_param2, nonref_marg_param1, nonref_marg_param2, nne, DD, zeta, ga, kasq, oo, grid_ne_idx, grid_ne_dist, probs, lb, ub, tol, maxit, nreport, verbose = TRUE, sam = FALSE) {
    .Call(`_dnnmp_predCeCopNNMP_covars`, obs, cop_family, cop_param, marg_family, ref_marg_param1, ref_marg_param2, nonref_marg_param1, nonref_marg_param2, nne, DD, zeta, ga, kasq, oo, grid_ne_idx, grid_ne_dist, probs, lb, ub, tol, maxit, nreport, verbose, sam)
}

qCEpois <- function(pp, rate, rate_fake, lower, upper, tol, maxit) {
    .Call(`_dnnmp_qCEpois`, pp, rate, rate_fake, lower, upper, tol, maxit)
}

qCEnbinom <- function(pp, size, mu, lower, upper, tol, maxit) {
    .Call(`_dnnmp_qCEnbinom`, pp, size, mu, lower, upper, tol, maxit)
}

logitGausWeight1_cpp <- function(nne, dist, zeta, mu, ka) {
    .Call(`_dnnmp_logitGausWeight1_cpp`, nne, dist, zeta, mu, ka)
}

logitGausWeight2_cpp <- function(nne, dist, zeta, mu, ka) {
    .Call(`_dnnmp_logitGausWeight2_cpp`, nne, dist, zeta, mu, ka)
}

